before_script:
  - export JAVA_HOME="C:\Program Files\Java\jdk-15.0.1

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - ./gradlew build

test-job:
  stage: test
  script:
    - echo "This job tests something"
    # - ./gradlew test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
