image: openjdk:15

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - echo "Building files"
    - ./gradlew assemble

test-job:
  stage: test
  script:
    - echo "Running tests"
    - ./gradlew test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys nothing yet."
